// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function BlockTarget(arg1:backend.BlockRequest):Promise<backend.BlockResult>;

export function GetBlocked():Promise<Array<backend.BlockedEntry>>;

export function GetInterfaceThroughput(arg1:string):Promise<backend.ThroughputData|boolean>;

export function GetPlatform():Promise<string>;

export function GetProcessDetails(arg1:Array<backend.InterfaceInfo>):Promise<Array<backend.ProcessDetail>>;

export function GetProcessIcon(arg1:number):Promise<string>;

export function GetProcessNetIO():Promise<Array<backend.ProcessNetIO>>;

export function GetThroughput():Promise<Array<backend.ThroughputData>>;

export function IsAdmin():Promise<boolean>;

export function QuickScan():Promise<backend.ScanResult>;

export function ScanNetwork(arg1:backend.ScanOptions):Promise<backend.ScanResult>;

export function UnblockTarget(arg1:string):Promise<backend.BlockResult>;
