// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockTarget(arg1) {
  return window['go']['main']['App']['BlockTarget'](arg1);
}

export function GetBlocked() {
  return window['go']['main']['App']['GetBlocked']();
}

export function GetInterfaceThroughput(arg1) {
  return window['go']['main']['App']['GetInterfaceThroughput'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProcessDetails(arg1) {
  return window['go']['main']['App']['GetProcessDetails'](arg1);
}

export function GetProcessIcon(arg1) {
  return window['go']['main']['App']['GetProcessIcon'](arg1);
}

export function GetProcessNetIO() {
  return window['go']['main']['App']['GetProcessNetIO']();
}

export function GetThroughput() {
  return window['go']['main']['App']['GetThroughput']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function QuickScan() {
  return window['go']['main']['App']['QuickScan']();
}

export function ScanNetwork(arg1) {
  return window['go']['main']['App']['ScanNetwork'](arg1);
}

export function UnblockTarget(arg1) {
  return window['go']['main']['App']['UnblockTarget'](arg1);
}
